name: scramble
description: "A fun and interactive word scramble and math challenge tool with OCR and file import support."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.1.0+6

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^10.3.10
  pdf: ^3.11.3
  printing: ^5.14.2
  excel: ^4.0.6
  syncfusion_flutter_pdf: ^32.2.9
  docx_to_text: ^1.0.1
  image_picker: ^1.2.1
  google_mlkit_text_recognition: ^0.15.1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"
